In [16]:
import pandas as pd

In [17]:

url = "https://reports-public.ieso.ca/public/Demand/PUB_Demand.csv"
df = pd.read_csv(url, comment="\\")
print(url)
df

https://reports-public.ieso.ca/public/Demand/PUB_Demand.csv

            Date  Hour  Market Demand  Ontario Demand
0     2026-01-01     1          19489           16526
1     2026-01-01     2          19317           16374
2     2026-01-01     3          19326           16242
3     2026-01-01     4          19070           16155
4     2026-01-01     5          19109           16180
...          ...   ...            ...             ...
1676  2026-03-11    21          19595           17495
1677  2026-03-11    22          19364           16763
1678  2026-03-11    23          18800           16087
1679  2026-03-11    24          18596           15517
1680  2026-03-12     1          18095           15164

[1681 rows x 4 columns]

In [18]:
url = "https://reports-public.ieso.ca/public/DemandZonal/PUB_DemandZonal.csv"
df = pd.read_csv(url)
print(url)
df

https://reports-public.ieso.ca/public/DemandZonal/PUB_DemandZonal.csv

,\\Hourly Zonal Demand Report,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,\\Created at 2026-03-12 08:00:14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,\\For 2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Date,Hour,Ontario Demand,Northwest,Northeast,Ottawa,East,Toronto,Essa,Bruce,Southwest,Niagara,West,Zone Total,Diff
3,2026-01-01,1,16526,688,1474,1049,1085,5568,1219,96,3000,569,1949,16697,171
4,2026-01-01,2,16374,686,1454,1024,1118,5451,1187,95,2926,563,2018,16522,148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,2026-03-11,20,18115,556,1460,1167,1287,6359,1248,104,3645,593,1735,18154,39
1679,2026-03-11,21,17495,554,1444,1111,1239,6187,1209,103,3537,573,1686,17643,148
1680,2026-03-11,22,16763,548,1415,1047,1171,5911,1132,98,3462,548,1582,16914,150
1681,2026-03-11,23,16087,538,1409,983,1103,5608,1096,94,3422,524,1545,16323,237
1682,2026-03-11,24,15517,525,1387,928,1045,5328,1034,91,3206,452,1543,15539,22

In [23]:
url = "https://reports-public.ieso.ca/public/DAHourlyEnergyLMP/PUB_DAHourlyEnergyLMP_20251212.csv"
df = pd.read_csv(url)
print(url)
df

https://reports-public.ieso.ca/public/DAHourlyEnergyLMP/PUB_DAHourlyEnergyLMP_20251212.csv

                                                          CREATED AT 2025/12/11 13:33:16 FOR 2025/12/12
Delivery Hour Pricing Location   LMP    Energy Loss Price                       Energy Congestion Price
1             ABITIBISF-LT.AG_T1 142.52 7.41                                                       0.00
2             ABITIBISF-LT.AG_T1 122.00 5.98                                                       0.00
3             ABITIBISF-LT.AG_T1 103.57 5.18                                                       0.00
4             ABITIBISF-LT.AG_T1 93.61  4.68                                                       0.00
...                                                                                                 ...
20            ZURICH-LT.AG_T1    195.50 -4.50                                                      0.00
21            ZURICH-LT.AG_T1    185.00 -5.00                                                      0.00
22            ZURICH-LT.AG_T1    159.93 -4.64                                                      0.00
23            ZURICH-LT.AG_T1    164.89 -5.11                                                      0.00
24            ZURICH-LT.AG_T1    121.13 -4.00                                                      0.00

[25009 rows x 1 columns]

In [ ]:
url = ""
df = pd.read_csv(url)
print(url)
df

In [21]:
## Bon lien ###url = "https://reports-public.ieso.ca/public/IntertieScheduleFlow/PUB_IntertieScheduleFlow.xml"
df = pd.read_csv(url)
print(url)
df

# Mauvais lien #https://reports-public.ieso.ca/public/IntertieScheduleFlow/PUB_IntertieScheduleFlow.csv
## Les donnees d'INertieScheduleFlow sont en XML, pas en csv,

https://reports-public.ieso.ca/public/IntertieScheduleFlow/PUB_IntertieScheduleFlow.xml

                  <?xml version="1.0" encoding="UTF-8"?>
0      <?xml-stylesheet type="text/xsl" href="https:/...
1                                         <IMODocHeader>
2      <DocTitle>Intertie Schedule and Flow Report</D...
3                           <DocRevision>2</DocRevision>
4                                   <DocConfidentiality>
...                                                  ...
22602                                          </Actual>
22603                                         </Actuals>
22604                                          </Totals>
22605                                      </IMODocBody>
22606                                     </IMODocument>

[22607 rows x 1 columns]

In [ ]:
# Mauvais lien "https://reports-public.ieso.ca/public/GenOutputbyFuelHourly/PUB_GenOutputbyFuelHourly.csv


url = ""
df = pd.read_csv(url)
print(url)
df

## Bon lien https://reports-public.ieso.ca/public/GenOutputbyFuelHourly/PUB_GenOutputbyFuelHourly.xml

In [ ]:
url = ""
df = pd.read_csv(url)
print(url)
df